# Generated by Django 4.0.2 on 2022-02-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj_app', '0002_alter_profile_name_alter_profile_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_amount',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
