# Generated by Django 4.0.2 on 2022-02-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj_app', '0004_alter_profile_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='total_amount',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
