# Generated by Django 4.0.2 on 2022-02-19 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj_app', '0005_alter_profile_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factor',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='madarkharj_app.group'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
