# Generated by Django 4.0.2 on 2022-06-14 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('madarkharj_app', '0006_alter_factor_group_alter_profile_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group_Profiles',
        ),
    ]
